
import { Geist, Geist_Mono, DM_Mono, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  subsets: ['latin'],
  weight: ['300', '500']
})

const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ['700']
})

export const metadata = {
  title: "Weather App Main",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmMono.variable} ${bricolageGrotesque.variable}`}>
        {children}
      </body>
    </html>
  );
}
